[tool.setuptools]
packages = ["altaron"]

[project]
name = "Altaron"
version = "0.0.0"
authors = [
  { name="Hasan Emir AkÄ±n", email="h.emirakn@gmail.com" },
]
description = ""
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]