[package]
name = "rbot"
version = "0.3.5"
edition = "2021"
exclude = ["test/**"]

[lib]
name = "rbot"
crate-type = ["cdylib", "rlib"]

[dependencies]
bybit = {path = "local_dependencies/bybit" }
binance = {path = "local_dependencies/binance" }

rbot_lib = {path= "local_dependencies/rbot_lib" }
rbot_session = {path= "local_dependencies/rbot_session" }
rbot_server = {path= "local_dependencies/rbot_server" }
rbot_market = {path= "local_dependencies/rbot_market" }
once_cell = { version = "1.19.0" }

console-subscriber = {version="0.2.0"}

tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18" }

# https://pyo3.rs/v0.13.2/faq
[dependencies.pyo3]
version = "0.20.3"
features = ["rust_decimal", "auto-initialize", "abi3-py38"]

[features]
extension-module = ["pyo3/extension-module"]
#default = ["extension-module"]
