[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "EasyOutput"
version = "0.0.7.1"
authors = [
  { name="FrankAustin", email="frankaustindev808@gmail.com" },
]
description = "Colored messages in the palm of your hand"
readme = "README.md"
requires-python = ">=3.12"
install_requires=['colorama']
classifiers=[
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Operating System :: Unix",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
]

[project.urls]
Homepage = "https://github.com/FrankAustin808/EasyOut/"
Issues = "https://github.com/FrankAustin808/EasyOut/issues/new/choose"