


#
#	agenda:
#		[ ] parse toml config for installations
#


#
#	publish: python3 moves/publish.py
#

#
#	not sure what this does:
#		python3 -m build --sdist 
#

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "voltaic"
version = "0.0.1"
dependencies = [
	"volts",
	"somatic",
	
	
	"click"
]

# license = { text = "license" }
license = { file = "license.s.HTML" }

description = ""
readme = "readme.md"


[project.scripts]
#
#	https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#creating-executable-scripts
#	from voltaic import clique; clique ()
#
# 	voltaic = "voltaic:clique"
#

[tool.setuptools.packages.find]
where = [ "venues/stages" ]

#
#	https://setuptools.pypa.io/en/latest/userguide/datafiles.html
#
[tool.setuptools.package-data]
"*" = [ "*.html", "*.HTML" ]




