[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "taxref"
version = "0.0.8"
authors = [
  { name="Samuel AndrÃ©s", email="samuel.andres@yahoo.fr" },
]
description = "A simple taxref toolbox."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.setuptools]
py-modules = ["taxref_common", "taxref11"]

[project.urls]
"Homepage" = "https://github.com/SamuelAndresPascal/cosmoloj-py"