[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mtok"
version = "4.1.2"
authors = [{ name = "Mahdi Mir", email = "imahdimir@gmail.com" }]
description = "Gets token by key"
readme = "README.md"
dependencies = [
    "requests",
]
