[tool.poetry]
authors = ["Craig Trim <craigtrim@gmail.com>"]

maintainers = ["Craig Trim <craigtrim@gmail.com>"]

description = "Offline Access to Enwiki Entities"
license = "MIT"
name = "enwiki-offline"
readme = "README.md"
version = "0.2.25"

keywords = ["utility", "helper", "text", "matching"]
repository = "https://github.com/craigtrim/enwiki-offline"

classifiers = [
  "Development Status :: 4 - Beta",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.11.5"
baseblock = "*"
dvc = "*"

[tool.poetry.dev-dependencies]
autopep8 = "*"
flakeheaven = "*"
plac = "*"
pre-commit = "*"
pytest = "*"

[tool.poetry.build]
generate-setup-file = true

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.flakeheaven]
base = "https://raw.githubusercontent.com/flakeheaven/flakeheaven/main/pyproject.toml"
exclude = ["__init__.py", "README.md", "setup.py", ".venv", ".git", "*_test.py"]
format = "grouped"
max_line_length = 500
show_source = true

[tool.flakeheaven.plugins]
"flake8-*" = ["+*"]
flake8-bandit = ["-*", "+S1??"]
flake8-docstrings = ["-*"]
pyflakes = ["+*", "-F401", "-F403"]
