[tool.poetry]
name = "pygnss"
version = "0.1.0"
description = ""
authors = ["Miquel Garcia <miquel.garcia@rokubun.cat>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.4"
pandas = "^2.2.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-mocha = "^0.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
