[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "postgresql-integration-test"
dynamic = ["version", "readme"]
authors = [{name = "Jason Camp", email = "me@jason.camp"},{name = "Ian Meyer", email = "k@imeyer.io"}]
license = {text = "Apache"}
description = "postgresql-integration-test is a python module that creates a temporary PostgreSQL instance to use for testing your application."
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11"
]

dependencies = [
    "psycopg2-binary >= 2.9.9",
    "pyyaml >= 6.0.1",
]

requires-python = ">=3.9"

[project.optional-dependencies]
tests = [
  "pytest >= 8.1.1",
  "pytest-env == 0.8.1",
  "pytest-cov == 4.0.0",
  "coverage >= 7.2.1",
  "mock == 5.0.1",
  "pytest-mock == 3.10.0",
  "pytest-skip-slow == 0.0.5"
]

[project.urls]
Homepage = "https://github.com/jasondcamp/postgresql-integration-test"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]
markers = [
    "settings_test:Check configuration options",
    "helpers_test:Check helper methods",
    "log_test:Check log methods",
    "integration_test:Check integration",
    "pgsql_test:Check postgresql methods",
    "version_test:Check version methods",
]

[tool.setuptools]
packages = ["postgresql_integration_test"]

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/markdown"}
version = {attr = "postgresql_integration_test.version.__version__"}
