[build-system]
requires = ["setuptools >= 61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gpx_vis"
version = "0.3.0"
authors = [
  { name="Jia Wei Teh", email="jiaweiteh.astro@gmail.com" },
]
description = "Plots your Komoot tours"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [    
    "folium",
    "numpy",
    "pandas",
    "humanfriendly",
    "cmasher",
    "reverse_geocode",
    "matplotlib",
    "vincenty",
    "gpxpy",
]