[tool.poetry]
name = "three_d_converter"
version = "0.1.0"
description = ""
authors = ["Ferhat Teker <ferhat.teker@hotmail.de>"]
readme = "README.md"
packages = [{include = "three_d_converter"}]

[tool.poetry.dependencies]
python = "^3.9"
uuid = "^1.30"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
