[tool.poetry]
name = "ibm-ara"
version = "0.1.1"
description = ""
authors = ["Shubham <Shubham.Shubham7@ibm.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"


[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"
requests-mock = "^1.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
