[tool.poetry]
name = "dataTransformationsBertas"
version = "0.2.0"
description = "Tool to automate data scientist daily work"
authors = ["Bertoldas"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = ">=1.9.3,<2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"