[tool.poetry]
name = "lazy-mongo-log"
version = "0.1.1"
description = ""
authors = ["MisterNyan <michael.edmund.wong@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
lazy-schema = "^0.1.0"
pymongo = "^4.6.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
