[project]
name = "syllogistic"
version = "0.0.42"
description = "A simple Lua build system for the TIC-80."
authors = [
    { name="Alastair McBain", email="mcbain.asm+syllogistic@gmail.com" }
]
readme = { file="README", content-type="text/plain" }
license = { file="LICENSE", content-type="text/plain" }
keywords = ["TIC-80", "Fantasy Console", "Build", "Build System", "LUA"]
classifiers = [
    "Environment :: Console",
    "License :: OSI Approved",
    "Development Status :: 4 - Beta",
]
requires-python = ">=3.11"

dependencies = [
    "pakettic~=1.3.1",
    "watchdog~=2.1.5",
]

[project.optional-dependencies]
dev = [
    "pytest~=5.2"
]

[project.scripts]
syllogistic = 'syllogistic.main:main'

[project.urls]
Homepage = "https://bitbucket.org/AMcBain/syllogistic"
Issues = "https://bitbucket.org/AMcBain/syllogistic/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
