[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "VideoOpinionMining"
version = "1.1"
authors = [
  { name="Artur Lima", email="vligmart@gmail.com" },
]
description = "This package receives an mp4 file classfying it according to its emotions and generating a heat map"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Labic-ICMC-USP/VEM"
"Example" = "https://colab.research.google.com/drive/1UqzA6bDgtZWGji652a0UjT7ZtDh3Xyi5?authuser=1#scrollTo=CKL-Mm9D18BB"