[project]
name = "Rryyz"
version = "0.0.1"
authors = [
  { name="魔法少女小蓉", email="1296811180@qq.com" },
]
description = "一个轻巧便捷的深度学习框架"
readme = "README.md"
requires-python = ">=3.3"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]