[project]
name = "shadowdragon"
version = "0.0.6"
authors = [
  { name="Kojin Glick", email="kglick@middlebury.edu" },
]
description = "An async wrapper for the ShadowDragon API"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "aiohttp"
]

[project.urls]
Homepage = "https://github.com/kojinglick-ctec/shadowdragon/"
Issues = "https://github.com/kojinglick-ctec/shadowdragon/issues"