[project]
name = "Doggel-Inc"
version = "1.4.2"
description = "A package with all DoggeÅ‚ Inc services"
readme = "README.md"
requires-python = ">=3.8"



authors = [
{name = "Lordpomind",email="lordpomind@gmail.com"},
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[build-system]


requires = ["setuptools>=61.0"]

build-backend = "setuptools.build_meta"